POWERCARD_POST_TYPE_ID = 1
CAREERS_POST_TYPE_ID = 2
EXPERIENCE_POST_TYPE_ID = 3

HELIO_PLAY_CATEGORY=1
HELIO_KIDS_CATEGORY=2
POWERCARD_FAQS_CATEGORY=3
NIGHT_LIFE_CATEGORY=4
REDEMPTION_STORE_CATEGORY=5

NIGHT_LIFE_KEY_QUERY='kq_night_life'
COFFEE_KEY_QUERY='kq_coffee'
REDEMPTION_STORE_KEY_QUERY='kq_redemption_store'