POWERCARD_POST_TYPE_ID = 1
CAREERS_POST_TYPE_ID = 2
EXPERIENCE_POST_TYPE_ID = 3

POWERCARD_CATEGORY=1
HELIO_PLAY_CATEGORY=2
HELIO_KIDS_CATEGORY=3
NIGHT_LIFE_CATEGORY=4
REDEMPTION_STORE_CATEGORY=5
OTHER_PRODUCT_CATEGORY=6

NIGHT_LIFE_KEY_QUERY='kq_night_life'
COFFEE_KEY_QUERY='kq_coffee'
REDEMPTION_STORE_KEY_QUERY='kq_redemption_store'