# key for decorator check_role_permission
# string value is equals record in model Model_name
banner = 'Banner'
event = 'Event'
feedback = 'Feedback'
fee = 'Fee'
game = 'Game'
faq = 'FAQ'
hot = 'Hot'
post = 'Post'
promotion_label = 'Promotion_Label'
notification = 'Notification'
promotion = 'Promotion'
denomination = 'Denomination'
hot_ads = 'Hot_Advs'
promotion_type = 'Promotion_Type'
advertisement = 'Advertisement'
link_card = 'Link_Card'
open_time = 'Open_Time'