# string value is equals record in model Model_name
banner = 'banner'
event = 'event'
feedback = 'feedback'
fee = 'fee'
game = 'game'
faq = 'faq'
hot = 'hot'
post = 'post'
promotion_label = 'promotion_label'
notification = 'notification'
promotion = 'promotion'
denomination = 'denomination'
hot_ads = 'hot_ads'
promotion_type = 'promotion_type'
advertisement = 'advertisement'
link_card = 'link_card'
open_time = 'open_time'