# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-20 04:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReloadInfomation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('order_id', models.CharField(max_length=100, verbose_name='Order ID')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('order_desc', models.TextField(verbose_name='Description')),
                ('order_status', models.CharField(choices=[('cancel', 'Cancel'), ('confirm_error', 'Confirm Error'), ('payment_error', 'Payment Error'), ('pendding', 'Pendding'), ('done', 'Done')], default='pendding', max_length=50)),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_booking_rel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
