# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-02 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_vnpay', '0004_reloadinfomation_transaction_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='reloadinfomation',
            name='fee',
            field=models.IntegerField(default=0, verbose_name='Fee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reloadinfomation',
            name='payment_amount',
            field=models.IntegerField(default=0, verbose_name='Payment Amount'),
            preserve_default=False,
        ),
    ]
