# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-02 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_vnpay', '0005_auto_20180702_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reloadinfomation',
            name='payment_amount',
            field=models.IntegerField(default=0, verbose_name='Payment Amount'),
        ),
    ]
