# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-13 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_vnpay', '0006_auto_20180702_1102'),
    ]

    operations = [
    	migrations.RunSQL(
		    sql=['ALTER TABLE api_vnpay_reloadinfomation CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;'],
		    reverse_sql=['ALTER TABLE api_vnpay_reloadinfomation CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;']  
		)
    ]

	