# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('name_vi', models.CharField(max_length=1000, null=True)),
                ('name_en', models.CharField(max_length=1000, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entertainment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('name_vi', models.CharField(max_length=2000, null=True)),
                ('name_en', models.CharField(max_length=2000, null=True)),
                ('image', models.ImageField(blank=True, max_length=1000, null=True, upload_to=b'')),
                ('short_description', models.TextField()),
                ('short_description_vi', models.TextField(null=True)),
                ('short_description_en', models.TextField(null=True)),
                ('content', models.TextField()),
                ('content_vi', models.TextField(null=True)),
                ('content_en', models.TextField(null=True)),
                ('location', models.CharField(max_length=250)),
                ('appropriate', models.CharField(max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entertainments_category_rel', to='core.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Entertainments_Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('name_vi', models.CharField(max_length=1000, null=True)),
                ('name_en', models.CharField(max_length=1000, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entertainments_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('name_vi', models.CharField(max_length=1000, null=True)),
                ('name_en', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('name_vi', models.CharField(max_length=1000, null=True)),
                ('name_en', models.CharField(max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, max_length=1000, null=True, upload_to=b'')),
                ('short_description', models.TextField()),
                ('content', models.TextField()),
                ('content_vi', models.TextField(null=True)),
                ('content_en', models.TextField(null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
            ],
        ),
        migrations.CreateModel(
            name='Event_Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('name_vi', models.CharField(max_length=1000, null=True)),
                ('name_en', models.CharField(max_length=1000, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('question_vi', models.CharField(max_length=1000, null=True)),
                ('question_en', models.CharField(max_length=1000, null=True)),
                ('answer', models.TextField()),
                ('answer_vi', models.TextField(null=True)),
                ('answer_en', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('name_vi', models.CharField(max_length=2000, null=True)),
                ('name_en', models.CharField(max_length=2000, null=True)),
                ('short_description', models.TextField()),
                ('short_description_vi', models.TextField(null=True)),
                ('short_description_en', models.TextField(null=True)),
                ('content', models.TextField()),
                ('content_vi', models.TextField(null=True)),
                ('content_en', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, max_length=1000, null=True, upload_to=b'')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_category_rel', to='core.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Game_Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('name_vi', models.CharField(max_length=1000, null=True)),
                ('name_en', models.CharField(max_length=1000, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('name_vi', models.CharField(max_length=1000, null=True)),
                ('name_en', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_url', models.CharField(max_length=1000)),
                ('image', models.ImageField(max_length=1000, upload_to=b'')),
                ('is_show', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('name_vi', models.CharField(max_length=2000, null=True)),
                ('name_en', models.CharField(max_length=2000, null=True)),
                ('image', models.ImageField(blank=True, max_length=1000, null=True, upload_to=b'')),
                ('short_description', models.TextField()),
                ('short_description_vi', models.TextField(null=True)),
                ('short_description_en', models.TextField(null=True)),
                ('content', models.TextField()),
                ('content_vi', models.TextField(null=True)),
                ('content_en', models.TextField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('key_query', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Post_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('name_vi', models.CharField(max_length=500, null=True)),
                ('name_en', models.CharField(max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts_type_rel', to='core.Post_Type'),
        ),
        migrations.AddField(
            model_name='game',
            name='game_filter',
            field=models.ManyToManyField(related_name='game_filter_rel', to='core.Game_Filter'),
        ),
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_type_rel', to='core.Game_Type'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_filter',
            field=models.ManyToManyField(related_name='events_filter_rel', to='core.Event_Filter'),
        ),
        migrations.AddField(
            model_name='entertainment',
            name='entertainments_filter',
            field=models.ManyToManyField(related_name='entertainments_filter_rel', to='core.Entertainments_Filter'),
        ),
        migrations.AddField(
            model_name='entertainment',
            name='entertainments_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entertainments_type_rel', to='core.Entertainments_Type'),
        ),
    ]
