# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entertainment',
            name='key_query',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='type',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='description_vi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
