# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-18 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20170713_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
