# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-25 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20180123_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_mapping',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='promotion_type',
            field=models.CharField(choices=[('popular', 'Popular'), ('users', 'Users'), ('users_divece', 'Users Device')], default='popular', max_length=50),
        ),
    ]
