# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-29 03:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20180125_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='sent_date',
            field=models.DateField(blank=True, null=True, verbose_name='Sent Date'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sent_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_user_rel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='sent_date',
            field=models.DateField(blank=True, null=True, verbose_name='Sent Date'),
        ),
    ]
