# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-30 03:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20180130_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='promotion_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_type_rel', to='core.Promotion_Type'),
        ),
    ]
