# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-02 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20180228_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='promotion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_promotion_rel', to='core.Promotion'),
        ),
    ]
