# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-06 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20180302_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hot_Advs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(max_length=1000, upload_to='hots')),
                ('is_register', models.BooleanField(default=False)),
                ('is_view_detail', models.BooleanField(default=False)),
                ('content', models.TextField()),
                ('sub_url_register', models.CharField(max_length=1000)),
                ('sub_url_view_detail', models.CharField(max_length=1000)),
                ('is_draft', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_role_rel', to='core.Roles'),
        ),
    ]
