# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-08 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20180306_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='is_save',
            field=models.BooleanField(default=False),
        ),
    ]
