# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-08 09:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_promotion_is_save'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_draft',
        ),
    ]
