# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-21 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_roles_permission'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fee',
            unique_together=set([('fee', 'fee_type', 'position')]),
        ),
    ]
