# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-21 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20180321_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_mapping',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
