# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-27 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20180321_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'verbose_name': 'Advertisement', 'verbose_name_plural': 'Advertisement'},
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Banner', 'verbose_name_plural': 'Banner'},
        ),
        migrations.AlterModelOptions(
            name='denomination',
            options={'verbose_name': 'Denomination', 'verbose_name_plural': 'Denomination'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Event'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQ'},
        ),
        migrations.AlterModelOptions(
            name='fee',
            options={'verbose_name': 'Fee', 'verbose_name_plural': 'Fee'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'FeedBack', 'verbose_name_plural': 'FeedBack'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Game', 'verbose_name_plural': 'Game'},
        ),
        migrations.AlterModelOptions(
            name='gift',
            options={'verbose_name': 'Gift', 'verbose_name_plural': 'Gift'},
        ),
        migrations.AlterModelOptions(
            name='hot',
            options={'verbose_name': 'Hot', 'verbose_name_plural': 'Hot'},
        ),
        migrations.AlterModelOptions(
            name='hot_advs',
            options={'verbose_name': 'Hot Advs', 'verbose_name_plural': 'Hot Advs'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Post'},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'verbose_name': 'Promotion', 'verbose_name_plural': 'Promotion'},
        ),
        migrations.AlterModelOptions(
            name='promotion_type',
            options={'verbose_name': 'Promotion Type', 'verbose_name_plural': 'Promotion Type'},
        ),
        migrations.AlterModelOptions(
            name='transaction_type',
            options={'verbose_name': 'Transaction Type', 'verbose_name_plural': 'Transaction Type'},
        ),
        migrations.AlterModelOptions(
            name='user_notification',
            options={'verbose_name': 'User Notification', 'verbose_name_plural': 'User Notification'},
        ),
        migrations.AddField(
            model_name='event',
            name='image_thumbnail',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='events', verbose_name='Image Thumbnail'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='is_show',
            field=models.BooleanField(default=False, verbose_name='Is show'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='name_vi',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(max_length=1000, upload_to='banners', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='is_show',
            field=models.BooleanField(default=False, verbose_name='Is show'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='position',
            field=models.IntegerField(verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='sub_url',
            field=models.CharField(max_length=1000, verbose_name='Sub url'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_vi',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_vi',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='category_notification',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='category_notification',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='category_notification',
            name='name_vi',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=500, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=500, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content_vi',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='events', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_draft',
            field=models.BooleanField(default=False, verbose_name='Is draft'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name_vi',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='short_description',
            field=models.CharField(max_length=350, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='short_description_en',
            field=models.CharField(max_length=350, null=True, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='short_description_vi',
            field=models.CharField(max_length=350, null=True, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(verbose_name='Start time'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(null=True, verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_vi',
            field=models.TextField(null=True, verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=255, unique=True, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_vi',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='fee',
            field=models.IntegerField(default=0, verbose_name='Fee'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='fee_type',
            field=models.CharField(choices=[('%', '%'), ('vnd', 'VND')], default='%', max_length=20, verbose_name='Fee type'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='is_apply',
            field=models.BooleanField(default=False, verbose_name='Is apply'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='position',
            field=models.CharField(choices=[('tickets', 'Ticket transfer fee'), ('deposit', 'Deposit fee')], default='tickets', max_length=50, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='answer',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=500, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('feedback', 'Feedback'), ('contact', 'Contact')], default='feedback', max_length=50, verbose_name='Feedback type'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='phone',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rate',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('no_process', 'No Process'), ('answered', 'Answered'), ('moved', 'Moved to related department')], default='no_process', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.CharField(max_length=500, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='game',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='game',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='game',
            name='content_vi',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='games', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='game',
            name='is_draft',
            field=models.BooleanField(default=False, verbose_name='Is draft'),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='game',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='game',
            name='name_vi',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='game',
            name='short_description',
            field=models.CharField(max_length=350, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='game',
            name='short_description_en',
            field=models.CharField(max_length=350, null=True, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='game',
            name='short_description_vi',
            field=models.CharField(max_length=350, null=True, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='hot',
            name='image',
            field=models.ImageField(max_length=1000, upload_to='hots', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='hot',
            name='is_show',
            field=models.BooleanField(default=False, verbose_name='Is show'),
        ),
        migrations.AlterField(
            model_name='hot',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='hot',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='hot',
            name='name_vi',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='hot',
            name='sub_url',
            field=models.CharField(max_length=1000, verbose_name='Sub url'),
        ),
        migrations.AlterField(
            model_name='hot_advs',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='hot_advs',
            name='image',
            field=models.ImageField(max_length=1000, upload_to='hots', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='hot_advs',
            name='is_register',
            field=models.BooleanField(default=False, verbose_name='Is register'),
        ),
        migrations.AlterField(
            model_name='hot_advs',
            name='is_view_detail',
            field=models.BooleanField(default=False, verbose_name='Is view detail'),
        ),
        migrations.AlterField(
            model_name='hot_advs',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='hot_advs',
            name='sub_url_register',
            field=models.CharField(max_length=1000, verbose_name='Sub url register'),
        ),
        migrations.AlterField(
            model_name='hot_advs',
            name='sub_url_view_detail',
            field=models.CharField(max_length=1000, verbose_name='Sub url view detail'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to=b'', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_QR_code',
            field=models.BooleanField(default=False, verbose_name='Is QR code'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message_en',
            field=models.TextField(null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message_vi',
            field=models.TextField(null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sub_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub url'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_vi',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='posts', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_draft',
            field=models.BooleanField(default=False, verbose_name='Is Draft'),
        ),
        migrations.AlterField(
            model_name='post',
            name='key_query',
            field=models.CharField(max_length=255, unique=True, verbose_name='Key query'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name_vi',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pin_to_top',
            field=models.BooleanField(default=False, verbose_name='Pin to top'),
        ),
        migrations.AlterField(
            model_name='post',
            name='short_description',
            field=models.CharField(max_length=350, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='short_description_en',
            field=models.CharField(max_length=350, null=True, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='short_description_vi',
            field=models.CharField(max_length=350, null=True, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='post_image',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='posts', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='post_type',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='post_type',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='post_type',
            name='description_vi',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='post_type',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='post_type',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='post_type',
            name='name_vi',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='QR_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcode', verbose_name='QR Code'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='content_vi',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='is_draft',
            field=models.BooleanField(default=False, verbose_name='Is draft'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='is_save',
            field=models.BooleanField(default=False, verbose_name='Is save'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='name_vi',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='short_description',
            field=models.CharField(max_length=350, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='short_description_en',
            field=models.CharField(max_length=350, null=True, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='short_description_vi',
            field=models.CharField(max_length=350, null=True, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='promotion_label',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='promotion_label',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='promotion_label',
            name='name_vi',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='promotion_type',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='roles_permission',
            name='model_name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='roles_permission',
            name='permission',
            field=models.CharField(choices=[('full', 'Full'), ('change', 'Change'), ('read', 'Read')], max_length=255, verbose_name='Permission'),
        ),
        migrations.AlterField(
            model_name='transaction_type',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='transaction_type',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='transaction_type',
            name='name_vi',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='type',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='type',
            name='description_detail',
            field=models.TextField(blank=True, null=True, verbose_name='Description detail'),
        ),
        migrations.AlterField(
            model_name='type',
            name='description_detail_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description detail'),
        ),
        migrations.AlterField(
            model_name='type',
            name='description_detail_vi',
            field=models.TextField(blank=True, null=True, verbose_name='Description detail'),
        ),
        migrations.AlterField(
            model_name='type',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='type',
            name='description_vi',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='type',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='types', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name_vi',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='type',
            name='sub_url',
            field=models.CharField(max_length=1000, verbose_name='Sub url'),
        ),
        migrations.AlterField(
            model_name='user_notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Is read'),
        ),
    ]
