# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-02 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20180327_0918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'User'},
        ),
        migrations.AddField(
            model_name='promotion',
            name='apply_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Apply time'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='subject',
            field=models.CharField(max_length=255, unique=True, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='subject_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='subject_vi',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Birth date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='personal_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Personal id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='User name'),
        ),
    ]
