# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-11 04:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20180402_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mode_Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('key', models.CharField(max_length=255, unique=True, verbose_name='Key')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'verbose_name': 'Roles', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterField(
            model_name='roles_permission',
            name='model_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_model_rel', to='core.Mode_Name'),
        ),
    ]
