# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-18 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20180411_1418'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roles_permission',
            unique_together=set([('model_name', 'role')]),
        ),
    ]
