# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-17 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_auto_20180418_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Is read'),
        ),
    ]
