# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-09 04:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20180517_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hot_advs',
            name='sub_url_register',
        ),
    ]
