# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-09 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_remove_hot_advs_sub_url_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hot_advs',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
    ]
